//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarGyms.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bitacora
    {
        public int IdBitacora { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public string NombreUsuario { get; set; }
        public Nullable<System.DateTime> FecRegistro { get; set; }
        public string Actividad { get; set; }
        public string Pantalla { get; set; }
        public string InformacionAdicional { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
