//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarGyms.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalendarioPago
    {
        public int IdTipoTabla { get; set; }
        public int IdPersona { get; set; }
        public Nullable<System.DateTime> FecVencimiento { get; set; }
        public Nullable<int> NoPago { get; set; }
        public Nullable<decimal> Capital { get; set; }
        public Nullable<decimal> Interes { get; set; }
        public Nullable<decimal> IVA { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<int> VersionTabla { get; set; }
        public Nullable<bool> Procesado { get; set; }
    
        public virtual Persona Persona { get; set; }
    }
}
