//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarGyms.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_Producto
    {
        public int IdProducto { get; set; }
        public string NombreCorto { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public Nullable<System.DateTime> FechaActualiza { get; set; }
        public int StockOriginal { get; set; }
        public int StockDisponible { get; set; }
        public string Codigo { get; set; }
        public decimal Capital { get; set; }
        public decimal IVA { get; set; }
        public decimal Total { get; set; }
    }
}
