//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarGyms.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatalogoGen
    {
        public int IdCatalogo { get; set; }
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public bool Default1 { get; set; }
        public bool Activo { get; set; }
    }
}
