//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarGyms.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consecutivo
    {
        public string NombreTabla { get; set; }
        public int IdConsecutivo { get; set; }
        public Nullable<System.DateTime> FecUltimoCambio { get; set; }
    }
}
