//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarGyms.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresa
    {
        public int IdEmpresa { get; set; }
        public string Empresa1 { get; set; }
        public string RFC { get; set; }
        public string RazonSocial { get; set; }
        public string DireccionEmpresa { get; set; }
        public string Telefono { get; set; }
        public string Representante { get; set; }
        public string AvisosEstadodeCuenta { get; set; }
    }
}
