//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarGyms.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paquete
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Paquete()
        {
            this.PersonaPaquetes = new HashSet<PersonaPaquete>();
        }
    
        public int IdPaquete { get; set; }
        public string Descripcion { get; set; }
        public string DatosExtras { get; set; }
        public decimal Costo { get; set; }
        public System.DateTime VigenciaIni { get; set; }
        public System.DateTime VigenciaFin { get; set; }
        public bool Activo { get; set; }
        public decimal PorcDescuento { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonaPaquete> PersonaPaquetes { get; set; }
    }
}
