//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarGyms.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parametro
    {
        public int IdParametro { get; set; }
        public Nullable<int> Id { get; set; }
        public string ValorParametroNumeric { get; set; }
        public string ValorParametroString { get; set; }
        public string ValorParametroDate { get; set; }
        public string TablaAsociada { get; set; }
        public string CampoAsociado { get; set; }
        public Nullable<decimal> Orden { get; set; }
    }
}
