//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarGyms.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonaPaquete
    {
        public int IdPersona { get; set; }
        public int IdPaquete { get; set; }
        public System.DateTime FechaPago { get; set; }
        public decimal Costo { get; set; }
        public System.DateTime FecRegistro { get; set; }
        public int IdUsuario { get; set; }
    
        public virtual Paquete Paquete { get; set; }
        public virtual Persona Persona { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
