//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarGyms.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Persona()
        {
            this.Contactoes = new HashSet<Contacto>();
            this.Movimientoes = new HashSet<Movimiento>();
            this.Pagoes = new HashSet<Pago>();
            this.PersonaDireccions = new HashSet<PersonaDireccion>();
            this.PersonaPaquetes = new HashSet<PersonaPaquete>();
            this.CalendarioPagos = new HashSet<CalendarioPago>();
        }
    
        public int IdPersona { get; set; }
        public string NombrePersona { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public Nullable<int> IdGenero { get; set; }
        public Nullable<System.DateTime> FechaNac { get; set; }
        public Nullable<int> IdTipoPersona { get; set; }
        public string RFC { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public string Email { get; set; }
        public int IdEstatusPersona { get; set; }
        public Nullable<int> Multiclub { get; set; }
        public Nullable<int> IdSucursal { get; set; }
        public int IdConocio { get; set; }
        public int IdObjetivo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contacto> Contactoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Movimiento> Movimientoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pago> Pagoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonaDireccion> PersonaDireccions { get; set; }
        public virtual Sucursale Sucursale { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonaPaquete> PersonaPaquetes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CalendarioPago> CalendarioPagos { get; set; }
    }
}
