//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarGyms.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelPagoMovimiento
    {
        public int IdPagoMovimiento { get; set; }
        public int IdPago { get; set; }
        public int IdMovimiento { get; set; }
        public Nullable<System.DateTime> FecAplicacion { get; set; }
        public Nullable<decimal> CapitalPagado { get; set; }
        public Nullable<decimal> InteresPagado { get; set; }
        public Nullable<decimal> IVAPagado { get; set; }
        public Nullable<decimal> TotalPagado { get; set; }
        public Nullable<bool> Estatus { get; set; }
        public Nullable<System.DateTime> FecUltimoCambio { get; set; }
        public Nullable<System.DateTime> FecCancelacion { get; set; }
        public Nullable<bool> Reaplicado { get; set; }
        public string CausaCancelacion { get; set; }
    
        public virtual Movimiento Movimiento { get; set; }
        public virtual Pago Pago { get; set; }
    }
}
