//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarGyms.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Telefono
    {
        public int IdPersona { get; set; }
        public Nullable<int> IdTipoTelefono { get; set; }
        public string Telefono1 { get; set; }
        public string NombreContacto { get; set; }
        public string Extension { get; set; }
    }
}
